# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false

# The general YaST agreement is 100 characters, so it fits into standard
# resolutions and Github's pull request view. But let's open the threshold a
# little bit
Metrics/LineLength:
  Max: 105

Metrics/BlockLength:
  # rspec is known as DSL with big blocks
  Exclude:
    - test/**/*

# some storage API have size method, but without empty? method
# for details see https://github.com/yast/yast-storage-ng/pull/83
Style/ZeroLengthPredicate:
  Enabled: false

# the ".freeze" attribute for the constants is not nice
Style/MutableConstant:
  Enabled: false

# this is failing in storage wrapper, it will need more time to adapt
Style/FrozenStringLiteralComment:
  Enabled: false

# workaround https://github.com/rubocop-hq/rubocop/issues/6861
Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - vg
    - md
    - lv
    - id
    - up
    - to
    - as
